name: myAWSTest

on: [push]

env:
  S3_BUCKET_NAME: my-aws-test-deploy
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'whatthe'
      - name: Build with Maven
        run: mvn -f demo/pom.xml --batch-mode --update-snapshots package
